export const API_BASE_URL = "https://uclapi.com/roombookings";
export const API_TOKEN = "uclapi-185f335809781b-69b449ec4bae9d-ec0730fa47fea9-5f1714806ba2a3";

export const MAX_RETRIES = 2;
export const CACHE_TODAY_MINUTES = 2;    // cache in minutes for today's bookings
export const CACHE_DEFAULT_MINUTES = 10; // cache in minutes for any other bookings
                                         // the reason for this: bookings made on the day
                                         // can be automatic and go through immediately

export const DEFAULT_ROOM_OPENING = "08:00"; // these are from the min/max values
export const DEFAULT_ROOM_CLOSING = "23:30"; // in the roombooking.ucl.ac.uk form

export const LATEST_OPENING = "10:00";   // these are just observed from manually sifting
export const EARLIEST_CLOSING = "21:00"; // through the data
                                         // they matter to help infer opening and closing times
                                         // see bookings/diaries.js

export const START_HOUR = 8; // these are the start & end hours that are used throughout the app
export const END_HOUR = 24;  // e.g. availability graphic start and ends in these and search form
                             // is autogenerated from them

export const NO_DATA_ERROR_MESSAGE = "There is no data for the given date.";
